# Generated by Django 4.2.2 on 2023-07-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('type', models.CharField(choices=[('Food', 'Food'), ('Gifts', 'Gifts'), ('Health', 'Health'), ('House', 'House'), ('Transport', 'Transport'), ('Personal Expense', 'Personal Expense'), ('Bills', 'Bills'), ('Trip', 'Trip'), ('Debts', 'Debts'), ('Other', 'Other')], max_length=16)),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('type', models.CharField(choices=[('Savings', 'Savings'), ('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Dividends', 'Dividends'), ('Other', 'Other')], max_length=10)),
            ],
            bases=('transactions.transaction',),
        ),
    ]
