# Generated by Django 4.1.7 on 2023-08-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_asset_bankaccount_cash_cashflow_liability_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='CashFlow',
        ),
        migrations.DeleteModel(
            name='Liability',
        ),
    ]
