# Generated by Django 4.1.7 on 2023-09-13 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
