# Generated by Django 4.1.7 on 2023-09-13 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_recurringtransaction_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cash',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
            preserve_default=False,
        ),
    ]
